run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - goconst
#    - gocritic
#    - gofmt
#    - goimports
    - golint
    - gosec
    - govet
    - ineffassign
    - maligned
    - misspell
    - nakedret
    - prealloc
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - misspell
    - errcheck
  disable:
    - gosimple

issues:
  exclude-rules:
    - text: &quot;Use of weak random number generator&quot;
      linters:
        - gosec
    - text: &quot;comment on exported var&quot;
      linters:
        - golint
    - text: &quot;don&#39;t use an underscore in package name&quot;
      linters:
        - golint
    - text: &quot;ST1003:&quot;
      linters:
        - stylecheck

linters-settings:
  goconst:
    min-occurrences: 4
  dogsled:
    max-blank-identifiers: 7
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
