version: 1
accounts:
  - name: user1
    coins: [&quot;1000token&quot;, &quot;10000000000stake&quot; ,&quot;1000000000rowan&quot; ,&quot;1000000000cdash&quot; ,&quot;1000000000ceth&quot; ]
  - name: user2
    coins: [&quot;1000token&quot;, &quot;100000000stake&quot; ,&quot;1000000000rowan&quot; ,&quot;1000000000cdash&quot;,&quot;1000000000ceth&quot;]
validator:
  name: user1
  staked: &quot;100000000stake&quot;
